version: '3'
networks:
  test-network:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/24    

services:
  dummy-userdb:
    build: ./tests/dummy-userdb
    image: artofimagination/dummy-userdb
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USER_STORE}:${USER_STORE_DOCKER}
    ports:
      - 8083:8083
    networks: 
      test-network:
        ipv4_address: 172.18.0.4
  backend:
    build: ./
    image: artofimagination/polygnosics
    ports:
      - 8082:8082
    volumes:
      - ${USER_STORE}:${USER_STORE_DOCKER}
    networks: 
      test-network:
        ipv4_address: 172.18.0.2
    depends_on:
      - dummy-userdb