version: '3'
networks:
  poly_backend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/24    

services:
  system-mysql:
    container_name: system-mysql
    image: "mysql:8.0.19"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: user_database
    ports:
      - ${MYSQL_DB_PORT}:${MYSQL_DB_PORT}
    volumes:
      - /srv/user-database:/var/lib/mysql
    networks: 
      - poly_backend
    command: >
      --server-id=1
      --port 3306
      --character-set-server=utf8
      --collation-server=utf8_general_ci
      --sync_binlog=1
      --binlog-format=ROW
      --bind-address=0.0.0.0
      --innodb_flush_log_at_trx_commit=1
      --relay_log_info_repository=TABLE
      --master_info_repository=TABLE
      --gtid-mode=ON
      --log-bin=mysql-bin
      --enforce-gtid-consistency
  backend:
    build: ./
    image: artofimagination/polygnosics-backend
    volumes:
      - ${USER_STORE}:${USER_STORE_DOCKER}
      - /var/run/docker.sock:/var/run/docker.sock
    networks: 
      - poly_backend
    depends_on:
      - system-mysql