production:
    dialect: mysql
    datasource: root@/core?parseTime=true
    dir: migrations
    table: migrations

development:
    dialect: mysql
    datasource: root@/core?parseTime=true
    dir: migrations
    table: migrations